version: 3
workdir: .
allow:
    depOnAnyVendor: false 
    deepScan: false


excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\\/test\\/.*$"
  - "vendor/"

vendors:
    3rd-cobra:
        in: github.com/spf13/cobra
    3rd-viper:
        in: github.com/spf13/viper
    3rd-cue:
        in: ['cuelang.org/go/cue', 'cuelang.org/go/cue/**']
    3rd-yaml:
        in: gopkg.in/yaml.v3
    3rd-openslo:
        in: ['github.com/OpenSLO/go-sdk/**']

components:
    Domain:
        in: ['internal/domain/**'] 
    
    Service:
        in: ['internal/service/**']

    CLI:
        in: ['cmd/convert', 'cmd/disruption', 'cmd/errorbudget', 'cmd/burnrate', 'cmd/feasibility', 'cmd/dependency', 'cmd/alerting']

    CLI-Root:
        in: ['cmd', 'cmd/sloak']

    Templates:
        in: ['templates/**']

    Util:
        in: ['internal/util/**']

    TestUtil:
        in: ['internal/testutil/**']

deps:
    Domain:
        mayDependOn: [Domain, Util] 
        canUse: []
        anyVendorDeps: true

    Service:
        mayDependOn: [Domain, Util, Templates]
        canUse: [3rd-cue, 3rd-yaml, 3rd-openslo]

    CLI:
        mayDependOn: [CLI, Domain, Util, Templates] 
        canUse: [3rd-cobra, 3rd-viper, 3rd-yaml]

    CLI-Root:
        mayDependOn: [CLI-Root, CLI, Domain, Service, Util, Templates]
        canUse: [3rd-cobra, 3rd-viper, 3rd-yaml]

    Templates:
        mayDependOn: []
        canUse: []
        anyProjectDeps: true

    Util:
        mayDependOn: []
        canUse: []
        anyVendorDeps: true

    TestUtil:
        mayDependOn: []
        canUse: []
        anyVendorDeps: true