version: 3
workdir: .
allow:
    depOnAnyVendor: false 
    deepScan: true


excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

vendors:
    3rd-cobra:
        in: github.com/spf13/cobra
    3rd-cue:
        in: ['cuelang.org/go/cue', 'cuelang.org/go/cue/**']
    3rd-yaml:
        in: gopkg.in/yaml.v3

components:
    Domain:
        in: ['internal/core/domain/**'] 
    
    Port:
        in: ['internal/core/port/**']

    Application:
        in: ['internal/core/service/**']

    Adapter:
        in: ['internal/adapter/**']
        
    CLI:
        in: ['cmd/**']

    Templates:
        in: ['templates/**']

    Util:
        in: ['internal/util/**']

    TestUtil:
        in: ['internal/testutil/**']

deps:
    Domain:
        mayDependOn: [Domain, Util] 
        canUse: []
        anyVendorDeps: true

    Port:
        mayDependOn: [Domain]
        canUse: []

    Application:
        mayDependOn: [Domain, Port, Util, Templates]
        canUse: [3rd-cue, 3rd-yaml]

    Adapter:
        mayDependOn: [Domain, Port, Application, Util] 
        canUse: []

    CLI:
        mayDependOn: [CLI, Domain, Port, Application, Util] 
        canUse: [3rd-cobra]

    Templates:
        mayDependOn: []
        canUse: []
        anyProjectDeps: true

    Util:
        mayDependOn: []
        canUse: []
        anyVendorDeps: true

    TestUtil:
        mayDependOn: []
        canUse: []
        anyVendorDeps: true